title: "DevOps & SRE AI Platforms Atlas 2025"
description: "Community-driven analysis of AI agent platforms for DevOps, SRE, and Platform Engineering"
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: # Optional: Add your GA tracking ID
