# docs/_config.yml
title: "DevOps & SRE AI Platforms — 2025 Atlas"
description: "A vendor-neutral, community-driven wiki about DevOps/SRE AI platforms"

# Default for project site; Actions injects the baseurl on build (see workflow)
url: "https://xdevops-ai.github.io"
baseurl: ""   # will be overridden by --baseurl in Actions

timezone: Europe/Bucharest

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap

last_modified_at:
  use_git_last_modified_date: true
  fallback_to_build_time: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - .github
  - .gitignore
  - package.json
  - package-lock.json

seo:
  name: "DevOps & SRE AI Platforms — 2025 Atlas"
  type: "Website"
