# Jekyll / GitHub Pages configuration for the DevOps & SRE AI Atlas

# --------------------
# Site metadata
# --------------------
title: "DevOps & SRE AI Platforms — 2025 Atlas"
description: "A vendor-neutral, community-driven wiki about DevOps/SRE AI platforms"
url: "https://xdevops-ai.github.io"          # org/user site URL
baseurl: "/devops-sre-ai-atlas-2025"         # repo name for project pages
timezone: Europe/Bucharest

# Optional fallbacks used in pages (Community links) if site.github is unavailable
repo_url: https://github.com/xdevops-ai/devops-sre-ai-atlas-2025
org_url:  https://github.com/xdevops-ai

# --------------------
# Build options
# --------------------
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
# Pretty URLs so links like /archetypes/ work (no .html needed)
permalink: pretty

# --------------------
# Theme
# --------------------
# Use a GitHub Pages supported remote theme (provides `layout: default`)
remote_theme: just-the-docs/just-the-docs

# Tell Just the Docs to load your custom stylesheet.
# The path is relative to the `docs/` directory.
just_the_docs:
  stylesheets:
    - /assets/css/just-the-docs-head-nav.css
# --------------------
# Plugins (all supported by GitHub Pages)
# --------------------
plugins:
  - jekyll-remote-theme       # required for remote_theme
  - jekyll-github-metadata    # enables site.github.*
  - jekyll-last-modified-at   # shows last modified timestamps (requires git history)
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# jekyll-last-modified-at configuration
last_modified_at:
  use_git_last_modified_date: true
  fallback_to_build_time: false

# --------------------
# Defaults
# --------------------
defaults:
  - scope:
      path: ""        # all files in docs/
      type: "pages"
    values:
      layout: "default"
      # Example usage on a page:
      # Last updated: {{ page.last_modified_at | date: "%B %-d, %Y" }}
      # Or build time: {{ site.time | date: "%B %-d, %Y" }}

# --------------------
# Exclusions
# --------------------
exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - .github
  - .gitignore
  - package.json
  - package-lock.json

# --------------------
# SEO defaults
# --------------------
seo:
  name: "DevOps & SRE AI Platforms — 2025 Atlas"
  type: "Website"

# --------------------
# (Optional) Sitemap options
# --------------------
# sitemap:
#   exclude:
#     - /assets/
#     - /vendor/
#   include_posts: false
