source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8" # for local `jekyll serve`
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-github-metadata"
gem "jekyll-last-modified-at"
# If you later pick a remote theme, also add:
gem "jekyll-remote-theme"
