name: Build & Deploy (Jekyll)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for jekyll-last-modified-at to read git history

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build site (Jekyll)
        working-directory: ./docs
        run: |
          bundle install
          # Compute a baseurl compatible with both project and org sites:
          # For project sites: "/<repo-name>"
          # For org/user sites (root): ""
          BASEURL=""
          if [ "${{ github.repository_owner }}" != "${{ github.event.repository.name }}" ]; then
            BASEURL="/${{ github.event.repository.name }}"
          fi
          echo "Using baseurl=$BASEURL"
          bundle exec jekyll build --baseurl "$BASEURL" --destination _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
